name: A Workflow for Greetings
on: push

jobs:
  build:
    name: Hello World Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions-a
        with:
          MY_NAME: "Velmani Karnan"
